export const SET_PLACES = 'SET_PLACES';
export const DELETE_PLACE = 'DELETE_PLACE';
export const PLACED_ADDED = 'PLACED_ADDED';
export const START_ADD_PLACE = 'START_ADD_PLACE';

export const TRY_AUTH = 'TRY_AUTH';

export const UI_START_LOADING = "UI_START_LOADING";
export const UI_STOP_LOADING = "UI_STOP_LOADING";

export const AUTH_SET_TOKEN = "AUTH_SET_TOKEN";
export const AUTH_REMOVE_TOKEN = "AUTH_REMOVE_TOKEN";

export const SET_HEROES = "SET_HEROES";
export const LOAD_MORE_HEROES = "LOAD_MORE_HEROES";
export const SET_HERO_DETAIL = "SET_HERO_DETAIL";
export const RESET_HEROES_FILTERS_AND_PAGINATION = "RESET_HEROES_FILTERS_AND_PAGINATION";
export const HERO_NAME_FILTER_CHANGED = 'HERO_NAME_FILTER_CHANGED';
export const HERO_INCREASE_OFFSET = 'HERO_INCREASE_OFFSET';

export const RESET_FILTERS = 'RESET_FILTERS';
export const NAME_STARTS_WITH_CHANGE = 'NAME_STARTS_WITH_CHANGE';

export const RESET_PAGINATION = 'RESET_PAGINATION';
export const INCREASE_PAGINATION_OFFSET = 'INCREASE_PAGINATION_OFFSET';

export const SET_COMICS = "SET_COMICS";
export const LOAD_MORE_COMICS = "LOAD_MORE_COMICS";
export const SET_COMIC_DETAIL = "SET_COMIC_DETAIL";
export const RESET_COMICS_FILTERS_AND_PAGINATION = "RESET_COMICS_FILTERS_AND_PAGINATION";
export const COMIC_NAME_FILTER_CHANGED = 'COMIC_NAME_FILTER_CHANGED';
export const COMIC_INCREASE_OFFSET = 'COMIC_INCREASE_OFFSET';

export const SET_STORIES = "SET_STORIES";
export const LOAD_MORE_STORIES = "LOAD_MORE_STORIES";
export const SET_STORY_DETAIL = "SET_STORY_DETAIL";
export const RESET_STORIES_FILTERS_AND_PAGINATION = "RESET_STORIES_FILTERS_AND_PAGINATION";
export const STORY_NAME_FILTER_CHANGED = 'STORY_NAME_FILTER_CHANGED';
export const STORY_INCREASE_OFFSET = 'STORY_INCREASE_OFFSET';
