export const HOME_SCREEN_NAME = 'HOME_SCREEN_NAME';
export const HEROES_SCREEN_NAME = 'HEROES_SCREEN_NAME';
export const HEROE_DETAIL_SCREEN_NAME = 'HEROE_DETAIL_SCREEN_NAME';
export const COMICS_SCREEN_NAME = 'COMICS_SCREEN_NAME';
export const COMIC_DETAIL_SCREEN_NAME = 'COMIC_DETAIL_SCREEN_NAME';
export const STORIES_SCREEN_NAME = 'STORIES_SCREEN_NAME';
export const STORY_DETAIL_SCREEN_NAME = 'STORY_DETAIL_SCREEN_NAME';
export const SIDEDRAWER_SCREEN_NAME = 'SIDEDRAWER_SCREEN_NAME';
